//! ItemKey → Steam `market_hash_name` bridge for the Sell Advisor.
//!
//! The save stores numeric item-type ids (`ItemKey`); Steam's market is keyed by `market_hash_name`.
//! `item_map.json` is the embedded bridge, regenerated by `tools/extract_items.py` straight from the
//! INSTALLED game's Unity Localization tables — so it tracks the live game (items an update adds included)
//! with no third-party datamine. Names + grades are computed from the key at lookup rather than enumerated:
//! a material's name is `names[key]`; a gear item's name is `names[base_id(key)]` and its grade is the
//! key's 3rd digit. Unknown ids (a base an update hasn't been re-extracted for) resolve to nothing and are
//! skipped — graceful degradation, never a misreport ([decision-save-read-only], INTENT §10).

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::OnceLock;

use serde::Deserialize;

/// Grade index (the ItemKey's 3rd digit) → grade name. Tradeable on Steam is Legendary and up (index ≥ 3);
/// Common/Uncommon/Rare are not listed, so they resolve to no candidates.
const GRADES: [&str; 10] = [
    "Common", "Uncommon", "Rare", "Legendary", "Immortal", "Arcana", "Beyond", "Celestial", "Divine",
    "Cosmic",
];
const FIRST_TRADEABLE_GRADE: usize = 3;

/// Cosmetic-only material metadata the localization doesn't carry (preserved across game updates by the
/// extractor); a new material with no entry falls back to a band-derived type and a neutral grade.
#[derive(Deserialize)]
struct Material {
    #[serde(rename = "type")]
    kind: String,
    grade: String,
    icon: String,
}

#[derive(Deserialize)]
struct ItemMap {
    /// id → English name, from the game's ItemTable: a material by its full key, a gear item by its base id.
    names: HashMap<i64, String>,
    /// gear base id → sprite path ("/game/…"); gear variants of a base share one sprite. Cosmetic.
    #[serde(rename = "gearIcons")]
    gear_icons: HashMap<i64, String>,
    /// material key → fx-class / grade / sprite. Cosmetic; see `Material`.
    materials: HashMap<i64, Material>,
}

/// Optional path to a backend-fetched item map on disk, set once at startup. The backend serves the map so
/// a game update reaches clients without a rebuild; if it's absent, stale, or unparseable we fall back to
/// the map embedded at build time — so the bridge always works offline.
static MAP_PATH: OnceLock<PathBuf> = OnceLock::new();

/// Point the bridge at the on-disk backend-fetched map (see `backend::refresh_item_map`). No-op if already
/// set. Must run before the first bridge lookup; the map is read lazily on first use.
pub fn set_map_path(path: PathBuf) {
    let _ = MAP_PATH.set(path);
}

fn map() -> &'static ItemMap {
    static MAP: OnceLock<ItemMap> = OnceLock::new();
    MAP.get_or_init(|| {
        MAP_PATH
            .get()
            .and_then(|p| std::fs::read_to_string(p).ok())
            .and_then(|s| serde_json::from_str(&s).ok())
            .unwrap_or_else(|| {
                serde_json::from_str(include_str!("item_map.json"))
                    .expect("embedded item_map.json is valid")
            })
    })
}

/// Item keys in the 1x band are materials/coins/soulstones (named by their full key); everything else that
/// resolves is gear.
fn is_material(item_key: i64) -> bool {
    item_key.to_string().starts_with('1')
}

/// A gear key's base-item id (drop the grade digit + trailing variant), under which the game names it —
/// and its grade index (3rd digit). Longer "chaotic" keys carry a 6-digit core we read the same way.
fn gear_base_and_grade(item_key: i64) -> Option<(i64, usize)> {
    let s = item_key.to_string();
    if s.len() < 6 {
        return None;
    }
    let base = format!("{}00{}", &s[0..2], &s[3..5]).parse().ok()?;
    let grade = s.as_bytes()[2].wrapping_sub(b'0') as usize;
    (grade < GRADES.len()).then_some((base, grade))
}

/// Ordered `market_hash_name` candidates to quote for an item type; empty = not market-tradeable.
/// Gear lists on Steam as "<name> (<grade>) <A|B|C>" — the game reuses the trailing letter per item line
/// and it isn't encoded in the key, so we offer all three plus the bare form; the caller quotes them in
/// order and takes the first that's actually listed.
pub fn market_hashes(item_key: i64) -> Vec<String> {
    let m = map();
    if is_material(item_key) {
        return m.names.get(&item_key).cloned().into_iter().collect();
    }
    if let Some((base, grade)) = gear_base_and_grade(item_key) {
        if grade >= FIRST_TRADEABLE_GRADE {
            if let Some(name) = m.names.get(&base) {
                let g = GRADES[grade];
                return vec![
                    format!("{name} ({g}) A"),
                    format!("{name} ({g}) B"),
                    format!("{name} ({g}) C"),
                    format!("{name} ({g})"),
                ];
            }
        }
    }
    Vec::new()
}

/// The Sell Advisor stash-filter category: a material's fx class (Decoration | Engraving | Inscription) or
/// coin/soulstone/crafting band, "Wearable" for market-tradeable gear. `None` for anything outside the
/// bridge (which the advisor skips anyway).
pub fn category(item_key: i64) -> Option<&'static str> {
    let m = map();
    if is_material(item_key) {
        return m.names.contains_key(&item_key).then(|| {
            m.materials
                .get(&item_key)
                .map(|mat| leak_kind(&mat.kind))
                .unwrap_or_else(|| material_band(item_key))
        });
    }
    market_tradeable_gear(m, item_key).then_some("Wearable")
}

/// The game's own sprite path ("/game/…") for the stash grid, or `None` outside the bridge. A brand-new
/// item with no preserved sprite yields an empty path (the grid shows a placeholder) — never wrong.
pub fn icon(item_key: i64) -> Option<&'static str> {
    let m = map();
    if is_material(item_key) {
        return m
            .names
            .contains_key(&item_key)
            .then(|| m.materials.get(&item_key).map(|mat| mat.icon.as_str()).unwrap_or(""));
    }
    gear_base_and_grade(item_key)
        .filter(|_| market_tradeable_gear(m, item_key))
        .map(|(base, _)| m.gear_icons.get(&base).map(String::as_str).unwrap_or(""))
}

/// The item's rarity grade (Common…Cosmic) for the stash grid's rarity colour. `None` outside the bridge.
pub fn grade(item_key: i64) -> Option<&'static str> {
    let m = map();
    if is_material(item_key) {
        return m.names.contains_key(&item_key).then(|| {
            m.materials.get(&item_key).map(|mat| leak_grade(&mat.grade)).unwrap_or("Common")
        });
    }
    gear_base_and_grade(item_key)
        .filter(|_| market_tradeable_gear(m, item_key))
        .map(|(_, gi)| GRADES[gi])
}

/// True when the key resolves to a listed gear item (base name known and grade tradeable).
fn market_tradeable_gear(m: &ItemMap, item_key: i64) -> bool {
    matches!(gear_base_and_grade(item_key), Some((base, grade))
        if grade >= FIRST_TRADEABLE_GRADE && m.names.contains_key(&base))
}

/// fx class from the material's key band, for a material the extractor hasn't tagged (a new one).
fn material_band(item_key: i64) -> &'static str {
    match &item_key.to_string()[..2] {
        "11" => "Decoration",
        "12" => "Engraving",
        "13" => "Inscription",
        "16" => "Coin",
        "19" => "Soulstone",
        _ => "Crafting",
    }
}

/// The stash filter compares against a fixed set of category labels, so a preserved material kind is one of
/// them; map it back to the corresponding `&'static str` (falling back to the band on anything unexpected).
fn leak_kind(kind: &str) -> &'static str {
    ["Decoration", "Engraving", "Inscription", "Coin", "Soulstone", "Crafting", "Wearable"]
        .into_iter()
        .find(|k| *k == kind)
        .unwrap_or("Crafting")
}

fn leak_grade(g: &str) -> &'static str {
    GRADES.into_iter().find(|x| *x == g).unwrap_or("Common")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn material_maps_to_its_plain_name() {
        assert_eq!(market_hashes(110001), vec!["Minor Ruby"]);
    }

    #[test]
    fn tradeable_gear_offers_grade_and_letter_variants() {
        assert_eq!(
            market_hashes(304011),
            vec![
                "Long Sword (Immortal) A",
                "Long Sword (Immortal) B",
                "Long Sword (Immortal) C",
                "Long Sword (Immortal)",
            ]
        );
    }

    /// Celestial/Divine/Cosmic became tradeable after launch; they hold the game's top values.
    #[test]
    fn top_grades_resolve() {
        assert_eq!(market_hashes(317171)[0], "Shadow Bow (Celestial) A");
        assert_eq!(market_hashes(519171)[0], "Dimensional Armor (Cosmic) A");
    }

    /// Items an update adds resolve straight from the freshly-extracted game names — the whole point of
    /// reading the live game. Eternal/Abyss list on Steam with the " C" suffix, which the candidate set covers.
    #[test]
    fn newly_added_items_resolve() {
        assert!(market_hashes(624193).contains(&"Abyss Ring (Immortal) C".to_string()));
        assert!(market_hashes(517141900).contains(&"Shine Armor (Celestial) C".to_string()));
        assert_eq!(grade(624193), Some("Immortal"));
        assert_eq!(category(624193), Some("Wearable"));
    }

    #[test]
    fn untradeable_grade_and_unknown_ids_map_to_nothing() {
        assert!(market_hashes(300001).is_empty()); // Long Sword (Common) — below tradeable grade
        assert!(market_hashes(312193).is_empty()); // Eternal Bow (Rare) — below tradeable grade
        assert!(market_hashes(999_999_999).is_empty()); // unknown base (e.g. not yet re-extracted)
    }

    #[test]
    fn category_classifies_materials_by_fx_and_gear_as_wearable() {
        assert_eq!(category(110001), Some("Decoration")); // Minor Ruby (gem)
        assert_eq!(category(120001), Some("Engraving")); // Goblin Hide (monster part)
        assert_eq!(category(304011), Some("Wearable")); // Long Sword (Immortal)
        assert_eq!(category(999_999_999), None); // unknown id
    }

    #[test]
    fn icon_resolves_to_the_game_sprite_path() {
        assert_eq!(icon(110001), Some("/game/items/materials/Item_110001.png")); // Minor Ruby
        assert_eq!(icon(304011).unwrap(), "/game/gear/sword/SWORD_300001.png"); // gear variants share the base sprite
        assert_eq!(icon(999_999_999), None); // unknown id
    }

    #[test]
    fn grade_resolves_for_gear_and_materials() {
        assert_eq!(grade(304011), Some("Immortal"));
        assert_eq!(grade(110001), Some("Common")); // Minor Ruby
        assert_eq!(grade(999_999_999), None);
    }
}
