//! ItemKey → Steam `market_hash_name` bridge for the Sell Advisor.
//!
//! The save stores numeric item-type ids (`ItemKey`); Steam's market is keyed by `market_hash_name`.
//! `item_map.json` is the embedded bridge, regenerated by `item_map.gen.cjs` from the MIT-licensed
//! `tbh-copilot` project's datamined tables (attribution there). It covers the same set that project's
//! "best to sell" feature does: market-tradeable gear plus the effect-materials. Tradeable grades are
//! Legendary/Immortal/Arcana/Beyond and — since the game opened them up after launch (verified live
//! 2026-07-07) — Celestial/Divine/Cosmic, which carry the highest values in the game. Unknown ids (e.g.
//! after a game update) map to nothing and are skipped — graceful degradation, never a misreport
//! ([decision-save-read-only], INTENT §10).

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

#[derive(Deserialize)]
struct GearName {
    name: String,
    grade: String,
    /// The game's own sprite path ("/game/…"), rendered by the visual stash grid from static/game/.
    icon: String,
}

#[derive(Deserialize)]
struct Material {
    /// The material's English name is already its `market_hash_name`.
    name: String,
    /// fx class — Decoration | Engraving | Inscription — surfaced as the Sell Advisor's stash filter.
    #[serde(rename = "type")]
    kind: String,
    /// The game's own sprite path ("/game/…"), rendered by the visual stash grid from static/game/.
    icon: String,
    /// Rarity grade (Common…Cosmic) — drives the stash grid's game-style rarity colour.
    grade: String,
}

#[derive(Deserialize)]
struct ItemMap {
    material: HashMap<i64, Material>,
    /// item_key → (name, grade); the hash is composed at lookup time.
    gear: HashMap<i64, GearName>,
}

fn map() -> &'static ItemMap {
    static MAP: OnceLock<ItemMap> = OnceLock::new();
    MAP.get_or_init(|| {
        serde_json::from_str(include_str!("item_map.json")).expect("embedded item_map.json is valid")
    })
}

/// Ordered `market_hash_name` candidates to quote for an item type; empty = not market-tradeable.
/// Gear is listed on Steam as "<name> (<grade>) A" (verified live); a few items drop the trailing
/// " A", so that variant is the fallback. The caller quotes candidates in order and takes the first hit.
pub fn market_hashes(item_key: i64) -> Vec<String> {
    let m = map();
    if let Some(mat) = m.material.get(&item_key) {
        return vec![mat.name.clone()];
    }
    if let Some(g) = m.gear.get(&item_key) {
        return vec![
            format!("{} ({}) A", g.name, g.grade),
            format!("{} ({})", g.name, g.grade),
        ];
    }
    Vec::new()
}

/// The Sell Advisor stash-filter category for an item type: the material's fx class
/// (Decoration | Engraving | Inscription) for materials, "Wearable" for market-tradeable gear.
/// `None` for anything outside the bridge — which the advisor skips anyway, so it never shows up to filter.
pub fn category(item_key: i64) -> Option<&'static str> {
    let m = map();
    if let Some(mat) = m.material.get(&item_key) {
        return Some(mat.kind.as_str());
    }
    if m.gear.contains_key(&item_key) {
        return Some("Wearable");
    }
    None
}

/// The game's own sprite path ("/game/…") for an item type, for the visual stash grid. `None` for
/// anything outside the bridge (the advisor skips those anyway). Served by the webview from static/game/.
pub fn icon(item_key: i64) -> Option<&'static str> {
    let m = map();
    if let Some(mat) = m.material.get(&item_key) {
        return Some(mat.icon.as_str());
    }
    m.gear.get(&item_key).map(|g| g.icon.as_str())
}

/// The item's rarity grade (Common…Cosmic), for the stash grid's game-style rarity colour. `None` for
/// anything outside the bridge.
pub fn grade(item_key: i64) -> Option<&'static str> {
    let m = map();
    if let Some(mat) = m.material.get(&item_key) {
        return Some(mat.grade.as_str());
    }
    m.gear.get(&item_key).map(|g| g.grade.as_str())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn material_maps_to_its_plain_name() {
        assert_eq!(market_hashes(110001), vec!["Minor Ruby"]);
    }

    #[test]
    fn tradeable_gear_maps_to_grade_suffixed_candidates() {
        assert_eq!(
            market_hashes(304011),
            vec!["Long Sword (Immortal) A", "Long Sword (Immortal)"]
        );
    }

    /// Celestial/Divine/Cosmic were untradeable at launch and the game opened them up later; they hold the
    /// game's top values, so a stale allowlist silently hid a player's most valuable stash items.
    #[test]
    fn top_grades_are_tradeable_since_the_game_opened_them_up() {
        assert_eq!(
            market_hashes(317171),
            vec!["Shadow Bow (Celestial) A", "Shadow Bow (Celestial)"]
        );
        assert_eq!(
            market_hashes(318171),
            vec!["Shadow Bow (Divine) A", "Shadow Bow (Divine)"]
        );
        assert_eq!(
            market_hashes(519171),
            vec!["Dimensional Armor (Cosmic) A", "Dimensional Armor (Cosmic)"]
        );
    }

    #[test]
    fn untradeable_grade_and_unknown_ids_map_to_nothing() {
        assert!(market_hashes(300001).is_empty()); // Long Sword (Common) — below tradeable grade
        assert!(market_hashes(999_999_999).is_empty()); // unknown id (e.g. post-update)
    }

    #[test]
    fn category_classifies_materials_by_fx_and_gear_as_wearable() {
        assert_eq!(category(110001), Some("Decoration")); // Minor Ruby (gem)
        assert_eq!(category(120001), Some("Engraving")); // Goblin Hide (monster part)
        assert_eq!(category(304011), Some("Wearable")); // Long Sword (Immortal)
        assert_eq!(category(999_999_999), None); // unknown id
    }

    #[test]
    fn icon_resolves_to_the_game_sprite_path() {
        assert_eq!(icon(110001), Some("/game/items/materials/Item_110001.png")); // Minor Ruby
        assert_eq!(icon(304011).unwrap(), "/game/gear/sword/SWORD_300001.png"); // Long Sword variants share the base sprite
        assert_eq!(icon(999_999_999), None); // unknown id
    }

    #[test]
    fn grade_resolves_for_gear_and_materials() {
        assert_eq!(grade(304011), Some("Immortal")); // Long Sword (Immortal)
        assert_eq!(grade(110001), Some("Common")); // Minor Ruby
        assert_eq!(grade(999_999_999), None); // unknown id
    }
}
