//! ItemKey → Steam `market_hash_name` bridge for the Sell Advisor.
//!
//! The save stores numeric item-type ids (`ItemKey`); Steam's market is keyed by `market_hash_name`.
//! `item_map.json` is the embedded bridge, regenerated by `item_map.gen.cjs` from the MIT-licensed
//! `tbh-copilot` project's datamined tables (attribution there). It covers the same set that project's
//! "best to sell" feature does: market-tradeable gear (grades Legendary/Immortal/Arcana/Beyond) plus the
//! effect-materials. Unknown ids (e.g. after a game update) map to nothing and are skipped — graceful
//! degradation, never a misreport ([decision-save-read-only], INTENT §10).

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

#[derive(Deserialize)]
struct GearName {
    name: String,
    grade: String,
}

#[derive(Deserialize)]
struct ItemMap {
    /// item_key → market_hash_name (the material's English name is already the hash).
    material: HashMap<i64, String>,
    /// item_key → (name, grade); the hash is composed at lookup time.
    gear: HashMap<i64, GearName>,
}

fn map() -> &'static ItemMap {
    static MAP: OnceLock<ItemMap> = OnceLock::new();
    MAP.get_or_init(|| {
        serde_json::from_str(include_str!("item_map.json")).expect("embedded item_map.json is valid")
    })
}

/// Ordered `market_hash_name` candidates to quote for an item type; empty = not market-tradeable.
/// Gear is listed on Steam as "<name> (<grade>) A" (verified live); a few items drop the trailing
/// " A", so that variant is the fallback. The caller quotes candidates in order and takes the first hit.
pub fn market_hashes(item_key: i64) -> Vec<String> {
    let m = map();
    if let Some(name) = m.material.get(&item_key) {
        return vec![name.clone()];
    }
    if let Some(g) = m.gear.get(&item_key) {
        return vec![
            format!("{} ({}) A", g.name, g.grade),
            format!("{} ({})", g.name, g.grade),
        ];
    }
    Vec::new()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn material_maps_to_its_plain_name() {
        assert_eq!(market_hashes(110001), vec!["Minor Ruby"]);
    }

    #[test]
    fn tradeable_gear_maps_to_grade_suffixed_candidates() {
        assert_eq!(
            market_hashes(304011),
            vec!["Long Sword (Immortal) A", "Long Sword (Immortal)"]
        );
    }

    #[test]
    fn untradeable_grade_and_unknown_ids_map_to_nothing() {
        assert!(market_hashes(300001).is_empty()); // Long Sword (Common) — below tradeable grade
        assert!(market_hashes(999_999_999).is_empty()); // unknown id (e.g. post-update)
    }
}
